сделала
dashasavochkina/market_test pull request #1
Opened 2024-04-15 04:49 UTC by dashasavochkina

2024-04-15 11:51 UTC, dashasavochkina commented on src/main/java/org/example/Main.java
> +package org.example;
этот фай удалить

2024-04-15 13:14 UTC, Diinal reviewed
Нужно доработать
Помимо написанных замечаний есть еще одно: коммит мессадж так себе) нужно через него описать то что ты сделала, в данном случае "Написан фреймворк АТ по Яндекс Маркету". 
Читай требования, там было про коммиты и то что лучше несколько маленьких чем один большой

2024-04-15 13:14 UTC, Diinal commented on .gitignore
> +.gradle
Много лишних гитигноров.
Нужны лишь те что действительно нужны в этом проекте

2024-04-15 13:14 UTC, Diinal commented on build.gradle
> +
отсутствует таск по сборке с тэгами.
За примерами сюда: https://git.moscow.alfaintra.net/projects/AUTOTEST/repos/risk_wsrm_autotest_java/browse/build.gradle

2024-04-15 13:14 UTC, Diinal commented on src/main/java/org/example/Main.java
> +package org.example;
Истинно так

2024-04-15 13:14 UTC, Diinal commented on src/test/java/pageObject/AbstractPage.java
> +public abstract class AbstractPage {
Зачем AbstractPage если в нем ничего нет?
хорошей практикой будет вынести сюда драйвер

2024-04-15 13:14 UTC, Diinal commented on src/test/java/pageObject/AbstractPage.java
> +package pageObject;
кэмэлкейс тут не допустим, имена пакетов пишутся в нижнем регистре
напиши просто pageobjects

2024-04-15 13:14 UTC, Diinal commented on src/test/java/pageObject/SmartphonesPage.java
> +    public WebDriver driver;
зачем паблик? Не безопасно
вынеси в абстракт пейдж и поставь модификатор protected

2024-04-15 13:14 UTC, Diinal commented on src/test/java/pageObject/SmartphonesPage.java
> +    @FindBy(xpath = "/html/body/div[1]/div/div[4]/div/div/div[1]/div/div/div[5]/div/div/div/div/div/div/div/div[2]/div/div/div/div[1]/div/div/noindex/div/button[2]")
плохой модификатор, на странице есть специальные атрибуты аля autotest-id. Используй их
Здесь и везде

2024-04-15 13:14 UTC, Diinal commented on src/test/java/pageObject/SmartphonesPage.java
> +    private final String productsPricesXPath = "//div[@data-apiary-widget-name='@light/Organic']//span[@data-auto='snippet-price-current']/span[1]";
XPath - мы не пишем, просто productsPrices

2024-04-15 13:14 UTC, Diinal commented on src/test/java/pageObject/SmartphonesPage.java
> +    public void changeMinPriceFilter(String value) {
setMinPriceFilter
вспоминаем SOLID, а именно первый принцип.
change = удалить содержимое и установить новое
set = установить содержимое, что у тебя и происходит

2024-04-15 13:14 UTC, Diinal commented on src/test/java/stepDefinitions/smartphones/PriceSortStepDefinitions.java
> +    @And("дожидаемся загрузки")
сколько ждем?
лучше параметризовать
дожидаемся загрузки 60 секунд, а далее 60 передаем в метод waitPreload()

2024-04-15 13:14 UTC, Diinal commented on src/test/java/pageObject/SmartphonesPage.java
> +        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(60));
Duration.ofSeconds(60) - 60 лучше параметризовать через шаг

2024-04-15 13:14 UTC, Diinal commented on src/test/java/pageObject/SmartphonesPage.java
> +    public void clearMinPriceFilter() {
где используется этот метод?

2024-04-15 13:14 UTC, Diinal commented on src/test/java/pageObject/SmartphonesPage.java
> +    public void clearMaxPriceFilter() {
где используется этот метод?

2024-04-15 13:14 UTC, Diinal commented on src/test/java/pageObject/SmartphonesPage.java
> +                (order.equals(SORT_DIR_ASC) && curPrice < prevPrice)
неверные условия
у тебя идет инверсия, а это всегда риск путаницы)
допустим у нас цены по возрастанию и в массиве следующие значения: 1 2 3 1
Твой метод вернет false уже при сравнении второго элемента: 2 > 1? ДА значит возращаем false, хотя сортировка была верная на сайте.

2024-04-15 13:14 UTC, Diinal commented on src/test/java/pageObject/SmartphonesPage.java
> +    public static final String SORT_DIR_ASC = "ASC";
можно упростить названия переменных до ACS и DESC

2024-04-15 13:14 UTC, Diinal commented on src/test/java/pageObject/SmartphonesPage.java
> +        ArrayList<Integer> productPrices = this.getProductPrices();
зачем this для константы?

2024-04-15 13:14 UTC, Diinal commented on src/test/java/pageObject/SmartphonesPage.java
> +    public int getProductCnt() {
getProductsCount - не экономь символы

2024-04-15 13:14 UTC, Diinal commented on src/test/java/pageObject/SmartphonesPage.java
> +        return driver.findElements(By.xpath(this.productsPricesXPath)).size();
зачем this?

2024-04-15 13:14 UTC, Diinal commented on src/test/resources/Smartphones/PriceFilter.feature
> +    Given пользователь находится на странице Смартфонов
лучше декомпозировать на 2 шага: открываем браузер и переходим на страницу смартфонов

2024-04-15 13:14 UTC, Diinal commented on src/test/resources/Smartphones/PriceFilter.feature
> +    Given пользователь выбирает сортировку подороже
откуда пользователь? просто "выбираем сортировку подороже"

2024-04-15 13:14 UTC, Diinal commented on src/test/java/pageObject/SmartphonesPage.java
> +    public int getNthProductPrice(int num) {
getProductPriceByRowNumber

2024-04-15 13:14 UTC, Diinal commented on src/test/java/pageObject/SmartphonesPage.java
> +        for (WebElement element : driver.findElements(By.xpath(this.productsPricesXPath))) {
очень сложно....

return getProductPrices().get(num-1)

а лучше передавать не номер а индекс(0,1,2 и тд) и делать 
return getProductPrices().get(index)

2024-04-15 13:14 UTC, Diinal commented on src/test/java/pageObject/SmartphonesPage.java
> +    private int textPriceToInt(String textPrice) {
convertStringPriceToInt

2024-04-15 13:14 UTC, Diinal commented on src/test/java/pageObject/SmartphonesPage.java
> +        Pattern pattern = Pattern.compile("\\d+");
Кажется можно упростить
Pattern pattern = Pattern.compile("^(\d+).*;(\d+)$");
Matcher matcher = pattern.matcher(textPrice);
return Integer.parseInt(matcher.group(1)+matcher.group(2));

2024-04-15 13:14 UTC, Diinal commented on src/test/java/stepDefinitions/smartphones/PriceFilterStepDefinitions.java
> +public class PriceFilterStepDefinitions {
Зачем класс без шагов?

2024-04-15 13:14 UTC, Diinal commented on src/test/java/stepDefinitions/smartphones/PriceSortStepDefinitions.java
> +public class PriceSortStepDefinitions {
Сделай BaseSteps класс в пакете steps.base
В BaseSteps объяви WebDriver driver;
PriceSortStepDefinitions наследуй от BaseSteps и переименуй в SortPriceSteps и положи в пакет steps

2024-04-15 13:14 UTC, Diinal commented on src/test/java/utils/Hooks.java
> +package utils;
это не утилита, в пакет steps.base

2024-04-15 13:14 UTC, Diinal commented on src/test/java/stepDefinitions/smartphones/PriceSortStepDefinitions.java
> +    WebDriver driver;
в BaseSteps

2024-04-15 13:14 UTC, Diinal commented on src/test/java/stepDefinitions/smartphones/PriceSortStepDefinitions.java
> +    SmartphonesPage currentPage;
currentPage != SmartphonesPage
тут неверно, нужен отдельный механизм по смене страниц

2024-04-15 13:14 UTC, Diinal commented on src/test/java/stepDefinitions/smartphones/PriceSortStepDefinitions.java
> +        driver = new ChromeDriver();
это все в хуки в Before
добавь только ошибку на случай не открытого браузера:
if (driver == null) {
throw new AtException("Браузер не открыт.")
}

2024-04-15 13:14 UTC, Diinal commented on src/test/java/stepDefinitions/smartphones/PriceSortStepDefinitions.java
> +        driver.get("https://market.yandex.ru/catalog--smartfony/26893750/list");
в отдельный шаг

2024-04-15 13:14 UTC, Diinal commented on src/test/java/utils/Hooks.java
> +    public void configureWebdriver() {
public void before()
тут мы инициализируем драйвер и передаем его в степы(BaseSteps.driver=driver;)

2024-04-15 13:14 UTC, Diinal commented on src/test/java/utils/Hooks.java
> +    }
```
@After
public void after() {
закрытие браузера...
}
```

2024-04-15 13:14 UTC, Diinal commented on src/test/java/stepDefinitions/smartphones/PriceSortStepDefinitions.java
> +    public void filterPriceMoreFirstProduct(float diff) {
diff лучше заменить на increment

2024-04-15 13:14 UTC, Diinal commented on src/test/java/stepDefinitions/smartphones/PriceSortStepDefinitions.java
> +    private final int IMPLICITLY_WAIT_TIMEOUT = 5;
в хуки

2024-04-15 13:14 UTC, Diinal commented on src/test/java/stepDefinitions/smartphones/PriceSortStepDefinitions.java
> +        driver.manage().timeouts().implicitlyWait(1, TimeUnit.SECONDS);
не очень хорошее решение менять неявное ожидание
лучше сделай через явное в методе
и в целом не очень понятно зачем его уменьшать

2024-04-15 13:14 UTC, Diinal commented on src/test/java/stepDefinitions/smartphones/PriceSortStepDefinitions.java
> +    public void closeBrowser() {
в хуки

2024-04-15 13:22 UTC, dashasavochkina commented on src/test/java/stepDefinitions/smartphones/PriceSortStepDefinitions.java
> +        driver.manage().timeouts().implicitlyWait(1, TimeUnit.SECONDS);
Ч добавила изменение ожидания на 1 секунду, так как тест без этого ждал бы 5 секунд появления товаров. А у нас этот метожд отрабатывает, когда мы и так уже до этого ждали загрузки waitPreload(). И часто мы бы ждали именно 5 секунд потому что из-за фильтров товаров бы и не назодилось. В общем 5 секунд очень долго. Но вообще согласна, переделаю на явное ожидание

2024-04-16 13:13 UTC, dashasavochkina commented on .gitignore
> +.gradle
готово

2024-04-16 13:18 UTC, dashasavochkina commented on src/test/java/stepDefinitions/smartphones/PriceFilterStepDefinitions.java
> +package stepDefinitions.smartphones;
камелкейс убрать

2024-04-16 13:22 UTC, dashasavochkina commented on src/test/java/pageObject/SmartphonesPage.java
> +    public WebDriver driver;
доступ паблик, тк идет обращение к этим переменным из другого пакета

2024-04-16 15:39 UTC, Diinal requested changes
При исправлении замечаний в рамках ревью нужно исправлять все замечания иначе ревьюер банально запутается

2024-04-16 15:39 UTC, Diinal commented on build.gradle
> +
Таски так и нет

2024-04-16 15:39 UTC, Diinal commented on src/test/java/pageobject/SmartphonesPage.java
> +    public WebDriver driver;
в AbstractPage с модификатором protected

2024-04-16 15:39 UTC, Diinal commented on src/test/java/pageobject/SmartphonesPage.java
> +        return (new WebDriverWait(driver, Duration.ofSeconds(1)))
принято использовать не больше 3-х методов в цепочке или по простому не более 3-х точек.
Декомпозируй немного
```
WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(1));
By productsPricesLocator =  By.xpath(this.productsPrices));
return wait.until(ExpectedConditions.presenceOfAllElementsLocatedBy(productsPricesLocator)).size();
```

Сами локаторы можно тоже писать сразу с типом By:
`private final By productsPrices = By.xpath("//div[@data-apiary-widget-name='@light/Organic']//span[@data-auto='snippet-price-current']/span[1]");`

Будет читабельней выглядеть = проще

2024-04-17 14:55 UTC, dashasavochkina commented on src/test/java/pageObject/SmartphonesPage.java
> +                (order.equals(SORT_DIR_ASC) && curPrice < prevPrice)
в данном примере будет сравнение не 2 > 1, а 2 < 1, тк у нас order = asc, и условие следующее:
(order.equals(SORT_DIR_ASC) && curPrice < prevPrice)
('asc'.equals('asc') && 2< 1), тк второе условие неверно, будет фолс условия, а значит if не выполнится и ретерна не будет.

2024-04-17 14:58 UTC, dashasavochkina commented on src/test/java/pageObject/SmartphonesPage.java
> +                (order.equals(SORT_DIR_ASC) && curPrice < prevPrice)
без инверсии не могу придумать

2024-04-17 15:00 UTC, dashasavochkina commented on src/test/java/pageObject/SmartphonesPage.java
> +        ArrayList<Integer> productPrices = this.getProductPrices();
не поняла

2024-04-17 15:25 UTC, dashasavochkina commented on src/test/java/stepDefinitions/smartphones/PriceSortStepDefinitions.java
> +public class PriceSortStepDefinitions {
при изменении названия пакета ломается кукумбер

2024-04-17 15:26 UTC, dashasavochkina commented on src/test/java/stepDefinitions/smartphones/PriceSortStepDefinitions.java
> +        driver = new ChromeDriver();
в хуках не получилось реализовать

2024-04-18 15:53 UTC, Diinal requested changes

2024-04-18 15:53 UTC, Diinal commented on src/test/java/utils/AbstractTestClass.java
> +public abstract class AbstractTestClass {
не нужон он нам

2024-04-18 15:53 UTC, Diinal commented on chromedriver.exe
в ресурсы

2024-04-18 15:53 UTC, Diinal commented on src/test/resources/Smartphones/PriceFilter.feature
> +Feature: Фильтрация смартфонов по стоимости
путь должен быть src/test/resources/features/PriceFilter.feature

2024-04-18 15:53 UTC, Diinal commented on src/test/resources/Smartphones/PriceFilter.feature
> +  @gui
не хватает уникальных тегов и тега `@all`

2024-04-18 15:53 UTC, Diinal commented on src/test/resources/Smartphones/PriceFilter.feature
> +  @gui
между сценариями должны быть пустые строки

2024-04-18 15:53 UTC, Diinal commented on src/test/resources/Smartphones/PriceFilter.feature
> +
в конце файла должны быть только 1 пустая строка.
Актуально дял !всех! файлов, не только фичей

2024-04-18 15:53 UTC, Diinal commented on src/test/java/utils/Hooks.java
> +        driver.close();
в метод destroyInstance

2024-04-18 15:53 UTC, Diinal commented on src/test/java/utils/Hooks.java
> +    @After
не хватает before

2024-04-18 20:33 UTC, dashasavochkina commented on src/main/java/org/example/Main.java
> +package org.example;
исправила

2024-04-18 20:34 UTC, dashasavochkina commented on .gitignore
> +.gradle
исправила

2024-04-18 20:34 UTC, dashasavochkina commented on build.gradle
> +
исправила

2024-04-18 20:34 UTC, dashasavochkina commented on src/test/java/pageObject/AbstractPage.java
> +public abstract class AbstractPage {
исправила

2024-04-18 20:36 UTC, dashasavochkina commented on src/test/java/pageObject/SmartphonesPage.java
> +    public WebDriver driver;
исправила

2024-04-18 20:36 UTC, dashasavochkina commented on src/test/java/pageObject/SmartphonesPage.java
> +    @FindBy(xpath = "/html/body/div[1]/div/div[4]/div/div/div[1]/div/div/div[5]/div/div/div/div/div/div/div/div[2]/div/div/div/div[1]/div/div/noindex/div/button[2]")
исправила

2024-04-18 20:36 UTC, dashasavochkina commented on src/test/java/pageObject/SmartphonesPage.java
> +    private final String productsPricesXPath = "//div[@data-apiary-widget-name='@light/Organic']//span[@data-auto='snippet-price-current']/span[1]";
исправила

2024-04-18 20:37 UTC, dashasavochkina commented on src/test/java/pageObject/SmartphonesPage.java
> +    public void changeMinPriceFilter(String value) {
исправила

2024-04-18 20:37 UTC, dashasavochkina commented on src/test/java/stepDefinitions/smartphones/PriceSortStepDefinitions.java
> +    @And("дожидаемся загрузки")
исправила

2024-04-18 20:47 UTC, dashasavochkina commented on src/test/java/pageObject/SmartphonesPage.java
> +        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(60));
исправила

2024-04-18 20:47 UTC, dashasavochkina commented on src/test/java/pageObject/SmartphonesPage.java
> +    public void clearMinPriceFilter() {
удалила

2024-04-18 20:48 UTC, dashasavochkina commented on src/test/java/pageObject/SmartphonesPage.java
> +    public void clearMaxPriceFilter() {
удалила

2024-04-18 20:48 UTC, dashasavochkina commented on src/test/java/pageObject/SmartphonesPage.java
> +    public static final String SORT_DIR_ASC = "ASC";
исправила

2024-04-18 20:48 UTC, dashasavochkina commented on src/test/java/pageObject/SmartphonesPage.java
> +    public int getProductCnt() {
исправила

2024-04-18 20:49 UTC, dashasavochkina commented on src/test/java/pageObject/SmartphonesPage.java
> +        return driver.findElements(By.xpath(this.productsPricesXPath)).size();
исправила

2024-04-18 20:49 UTC, dashasavochkina commented on src/test/resources/Smartphones/PriceFilter.feature
> +    Given пользователь находится на странице Смартфонов
исправила

2024-04-18 20:49 UTC, dashasavochkina commented on src/test/resources/Smartphones/PriceFilter.feature
> +    Given пользователь выбирает сортировку подороже
исправила

2024-04-18 20:49 UTC, dashasavochkina commented on src/test/java/pageObject/SmartphonesPage.java
> +    public int getNthProductPrice(int num) {
исправила

2024-04-18 20:49 UTC, dashasavochkina commented on src/test/java/pageObject/SmartphonesPage.java
> +        for (WebElement element : driver.findElements(By.xpath(this.productsPricesXPath))) {
исправила

2024-04-18 20:49 UTC, dashasavochkina commented on src/test/java/pageObject/SmartphonesPage.java
> +    private int textPriceToInt(String textPrice) {
исправила

2024-04-18 20:49 UTC, dashasavochkina commented on src/test/java/pageObject/SmartphonesPage.java
> +        Pattern pattern = Pattern.compile("\\d+");
исправила

2024-04-18 20:50 UTC, dashasavochkina commented on src/test/java/stepDefinitions/smartphones/PriceFilterStepDefinitions.java
> +public class PriceFilterStepDefinitions {
удалила

2024-04-18 20:50 UTC, dashasavochkina commented on src/test/java/stepDefinitions/smartphones/PriceSortStepDefinitions.java
> +public class PriceSortStepDefinitions {
исправила

2024-04-18 20:50 UTC, dashasavochkina commented on src/test/java/utils/Hooks.java
> +package utils;
исправила

2024-04-18 20:50 UTC, dashasavochkina commented on src/test/java/stepDefinitions/smartphones/PriceSortStepDefinitions.java
> +    WebDriver driver;
исправила

2024-04-18 20:52 UTC, dashasavochkina commented on src/test/java/stepDefinitions/smartphones/PriceSortStepDefinitions.java
> +        driver = new ChromeDriver();
исправила

2024-04-18 20:52 UTC, dashasavochkina commented on src/test/java/stepDefinitions/smartphones/PriceSortStepDefinitions.java
> +        driver.get("https://market.yandex.ru/catalog--smartfony/26893750/list");
исправила

2024-04-18 20:53 UTC, dashasavochkina commented on src/test/java/utils/Hooks.java
> +    public void configureWebdriver() {
исправила

2024-04-18 20:53 UTC, dashasavochkina commented on src/test/java/utils/Hooks.java
> +    }
исправила

2024-04-18 20:53 UTC, dashasavochkina commented on src/test/java/stepDefinitions/smartphones/PriceSortStepDefinitions.java
> +    public void filterPriceMoreFirstProduct(float diff) {
исправила

2024-04-18 20:54 UTC, dashasavochkina commented on src/test/java/stepDefinitions/smartphones/PriceSortStepDefinitions.java
> +    private final int IMPLICITLY_WAIT_TIMEOUT = 5;
поместила в driverManager

2024-04-18 20:55 UTC, dashasavochkina commented on src/test/java/stepDefinitions/smartphones/PriceSortStepDefinitions.java
> +    SmartphonesPage currentPage;
обсудили сегодня, по-другому не получится

2024-04-18 21:56 UTC, dashasavochkina commented on src/test/java/stepDefinitions/smartphones/PriceSortStepDefinitions.java
> +    public void closeBrowser() {
исправила

2024-04-18 21:58 UTC, dashasavochkina commented on src/test/java/utils/Hooks.java
> +    @After
исправила

2024-04-18 21:58 UTC, dashasavochkina commented on src/test/java/utils/Hooks.java
> +        driver.close();
исправила

2024-04-18 21:59 UTC, dashasavochkina commented on src/test/resources/Smartphones/PriceFilter.feature
> +
исправила

2024-04-18 21:59 UTC, dashasavochkina commented on src/test/resources/Smartphones/PriceFilter.feature
> +  @gui
исправила

2024-04-18 22:00 UTC, dashasavochkina commented on src/test/resources/Smartphones/PriceFilter.feature
> +Feature: Фильтрация смартфонов по стоимости
исправила

2024-04-18 22:00 UTC, dashasavochkina commented on chromedriver.exe
исправила

2024-04-18 22:00 UTC, dashasavochkina commented on src/test/java/utils/AbstractTestClass.java
> +public abstract class AbstractTestClass {
исправила

2024-04-18 22:01 UTC, dashasavochkina commented on src/test/java/pageobject/SmartphonesPage.java
> +        return (new WebDriverWait(driver, Duration.ofSeconds(1)))
поменяла логику

2024-04-18 22:02 UTC, dashasavochkina commented on src/test/java/pageobject/SmartphonesPage.java
> +    public WebDriver driver;
исправила

2024-04-18 22:02 UTC, dashasavochkina commented on src/test/java/stepDefinitions/smartphones/PriceFilterStepDefinitions.java
> +package stepDefinitions.smartphones;
исправила

2024-04-18 22:04 UTC, dashasavochkina commented on src/test/java/pageObject/SmartphonesPage.java
> +        Pattern pattern = Pattern.compile("\\d+");
не работает для чисел <1000, >=1000000

2024-04-19 08:54 UTC, Diinal requested changes

2024-04-19 08:54 UTC, Diinal commented on src/test/java/steps/SmartphonesSteps.java
>      SmartphonesPage currentPage;
`SmartphonesPage smartphonesPage`

2024-04-19 08:54 UTC, Diinal commented on src/test/java/pageobjects/SmartphonesPage.java
>      public int getProductPriceByRowNumber(int index) {
Если используешь индексы - переименуй метод в `getProductPriceByRowIndex`

2024-04-19 08:54 UTC, Diinal commented on src/test/java/steps/base/Hooks.java
> +        DriverManager.getInstance();
raw use
такое не приветствуется, должна быть цель вызова метода
хукам инстанс драйвера не нужен, он нужен степам для инициализации пэйджобджектов
Сделай так:
BaseSteps.driver = DriverManager.getInstance();

в BaseSteps соответственно оставь только объявление атрибута, без инициализации

2024-04-19 09:27 UTC, dashasavochkina commented on src/test/java/pageobjects/SmartphonesPage.java
>      public int getProductPriceByRowNumber(int index) {
исправила

2024-04-19 09:27 UTC, dashasavochkina commented on src/test/java/steps/SmartphonesSteps.java
>      SmartphonesPage currentPage;
исправила

2024-04-19 09:27 UTC, dashasavochkina commented on src/test/java/steps/base/Hooks.java
> +        DriverManager.getInstance();
исправила

2024-04-19 09:32 UTC, Diinal approved these changes

2024-05-02 10:36 UTC, merged